"""Separate structured outcome-code domains for trusted primitives."""

from dataclasses import dataclass
from enum import Enum


class DecisionReasonCode(Enum):
    """Reason codes belonging only to policy/action decisions."""

    UNSPECIFIED = "UNSPECIFIED"


class ParseFailureCode(Enum):
    INVALID_INPUT_TYPE = "INVALID_INPUT_TYPE"
    INVALID_LIMITS = "INVALID_LIMITS"
    BYTE_LIMIT_EXCEEDED = "BYTE_LIMIT_EXCEEDED"
    INVALID_UTF8 = "INVALID_UTF8"
    UTF8_BOM = "UTF8_BOM"
    DEPTH_LIMIT_EXCEEDED = "DEPTH_LIMIT_EXCEEDED"
    INVALID_JSON = "INVALID_JSON"
    DUPLICATE_MEMBER = "DUPLICATE_MEMBER"
    INVALID_UNICODE_SCALAR = "INVALID_UNICODE_SCALAR"
    INVALID_NUMBER = "INVALID_NUMBER"
    NUMBER_LIMIT_EXCEEDED = "NUMBER_LIMIT_EXCEEDED"


class IdentityValidationFailureCode(Enum):
    INVALID_TYPE = "INVALID_TYPE"
    INVALID_LENGTH = "INVALID_LENGTH"
    INVALID_FORMAT = "INVALID_FORMAT"


class ManifestFailureCode(Enum):
    INVALID_INPUT_TYPE = "INVALID_INPUT_TYPE"
    BYTE_LIMIT_EXCEEDED = "BYTE_LIMIT_EXCEEDED"
    PARSE_FAILED = "PARSE_FAILED"
    INVALID_TOP_LEVEL = "INVALID_TOP_LEVEL"
    UNKNOWN_FIELD = "UNKNOWN_FIELD"
    MISSING_FIELD = "MISSING_FIELD"
    INVALID_FIELD_TYPE = "INVALID_FIELD_TYPE"
    INVALID_FIELD_VALUE = "INVALID_FIELD_VALUE"
    DUPLICATE_IDENTITY = "DUPLICATE_IDENTITY"
    UNKNOWN_RESOURCE_REFERENCE = "UNKNOWN_RESOURCE_REFERENCE"
    RESOURCE_KIND_MISMATCH = "RESOURCE_KIND_MISMATCH"
    INVALID_PREDECESSOR = "INVALID_PREDECESSOR"
    EMPTY_REQUIRED_SET = "EMPTY_REQUIRED_SET"


class ResourceFailureCode(Enum):
    INVALID_INPUT_TYPE = "INVALID_INPUT_TYPE"
    INLINE_BYTE_LIMIT_EXCEEDED = "INLINE_BYTE_LIMIT_EXCEEDED"
    DIGEST_MISMATCH = "DIGEST_MISMATCH"
    RESOURCE_KIND_MISMATCH = "RESOURCE_KIND_MISMATCH"
    JSON_BYTE_LIMIT_EXCEEDED = "JSON_BYTE_LIMIT_EXCEEDED"
    PARSE_FAILED = "PARSE_FAILED"


class TargetRegistrationFailureCode(Enum):
    INVALID_INPUT_TYPE = "INVALID_INPUT_TYPE"
    BYTE_LIMIT_EXCEEDED = "BYTE_LIMIT_EXCEEDED"
    PARSE_FAILED = "PARSE_FAILED"
    INVALID_TOP_LEVEL = "INVALID_TOP_LEVEL"
    MISSING_FIELD = "MISSING_FIELD"
    UNKNOWN_FIELD = "UNKNOWN_FIELD"
    INVALID_FIELD_TYPE = "INVALID_FIELD_TYPE"
    INVALID_FIELD_VALUE = "INVALID_FIELD_VALUE"
    DUPLICATE_IDENTITY = "DUPLICATE_IDENTITY"
    EMPTY_REQUIRED_SET = "EMPTY_REQUIRED_SET"
    INCONSISTENT_CONFIGURATION = "INCONSISTENT_CONFIGURATION"


class AuthorizationProposalFailureCode(Enum):
    INVALID_INPUT_TYPE = "INVALID_INPUT_TYPE"
    BYTE_LIMIT_EXCEEDED = "BYTE_LIMIT_EXCEEDED"
    PARSE_FAILED = "PARSE_FAILED"
    INVALID_TOP_LEVEL = "INVALID_TOP_LEVEL"
    MISSING_FIELD = "MISSING_FIELD"
    UNKNOWN_FIELD = "UNKNOWN_FIELD"
    INVALID_FIELD_TYPE = "INVALID_FIELD_TYPE"
    INVALID_FIELD_VALUE = "INVALID_FIELD_VALUE"
    DUPLICATE_IDENTITY = "DUPLICATE_IDENTITY"
    EMPTY_REQUIRED_SET = "EMPTY_REQUIRED_SET"
    INCONSISTENT_CONFIGURATION = "INCONSISTENT_CONFIGURATION"


class IssueContractFailureCode(Enum):
    INVALID_INPUT_TYPE = "INVALID_INPUT_TYPE"
    BYTE_LIMIT_EXCEEDED = "BYTE_LIMIT_EXCEEDED"
    PARSE_FAILED = "PARSE_FAILED"
    INVALID_TOP_LEVEL = "INVALID_TOP_LEVEL"
    MISSING_FIELD = "MISSING_FIELD"
    UNKNOWN_FIELD = "UNKNOWN_FIELD"
    INVALID_FIELD_TYPE = "INVALID_FIELD_TYPE"
    INVALID_FIELD_VALUE = "INVALID_FIELD_VALUE"
    DUPLICATE_IDENTITY = "DUPLICATE_IDENTITY"
    EMPTY_REQUIRED_SET = "EMPTY_REQUIRED_SET"
    INCONSISTENT_CONFIGURATION = "INCONSISTENT_CONFIGURATION"


class TargetRegistrationAdmissionReasonCode(Enum):
    ADMITTED = "ADMITTED"
    AUTHENTICATED_APPROVAL_UNAVAILABLE = "AUTHENTICATED_APPROVAL_UNAVAILABLE"
    POLICY_CONTEXT_UNAVAILABLE = "POLICY_CONTEXT_UNAVAILABLE"
    ROOT_ASSESSMENT_UNAVAILABLE = "ROOT_ASSESSMENT_UNAVAILABLE"
    IDENTITY_MISMATCH = "IDENTITY_MISMATCH"
    POLICY_EPOCH_MISMATCH = "POLICY_EPOCH_MISMATCH"
    REPOSITORY_MISMATCH = "REPOSITORY_MISMATCH"
    ADMIN_NOT_PERMITTED = "ADMIN_NOT_PERMITTED"
    ROOT_IMPACT = "ROOT_IMPACT"
    ROOT_IMPACT_INDETERMINATE = "ROOT_IMPACT_INDETERMINATE"
    POLICY_CAPABILITY_VIOLATION = "POLICY_CAPABILITY_VIOLATION"
    POLICY_SCOPE_VIOLATION = "POLICY_SCOPE_VIOLATION"
    POLICY_RISK_VIOLATION = "POLICY_RISK_VIOLATION"
    RISK_RELATION_UNAVAILABLE = "RISK_RELATION_UNAVAILABLE"
    POLICY_SERVICE_IDENTITY_VIOLATION = "POLICY_SERVICE_IDENTITY_VIOLATION"
    POLICY_CONFIG_VIOLATION = "POLICY_CONFIG_VIOLATION"


class AuthorizationAdmissionReasonCode(Enum):
    ADMITTED = "ADMITTED"
    AUTHENTICATED_APPROVAL_UNAVAILABLE = "AUTHENTICATED_APPROVAL_UNAVAILABLE"
    TARGET_CONTEXT_UNAVAILABLE = "TARGET_CONTEXT_UNAVAILABLE"
    POLICY_CONTEXT_UNAVAILABLE = "POLICY_CONTEXT_UNAVAILABLE"
    CONTRACT_CONTEXT_UNAVAILABLE = "CONTRACT_CONTEXT_UNAVAILABLE"
    ISSUER_AUTHORITY_UNAVAILABLE = "ISSUER_AUTHORITY_UNAVAILABLE"
    TARGET_REGISTRATION_MISMATCH = "TARGET_REGISTRATION_MISMATCH"
    POLICY_EPOCH_MISMATCH = "POLICY_EPOCH_MISMATCH"
    AUTHENTICATION_BINDING_MISMATCH = "AUTHENTICATION_BINDING_MISMATCH"
    CONTRACT_BINDING_MISMATCH = "CONTRACT_BINDING_MISMATCH"
    PARENT_AUTHORIZATION_UNAVAILABLE = "PARENT_AUTHORIZATION_UNAVAILABLE"
    PARENT_AUTHORIZATION_MISMATCH = "PARENT_AUTHORIZATION_MISMATCH"
    PARENT_TARGET_MISMATCH = "PARENT_TARGET_MISMATCH"
    PARENT_POLICY_EPOCH_MISMATCH = "PARENT_POLICY_EPOCH_MISMATCH"
    DELEGATION_DEPTH_EXCEEDED = "DELEGATION_DEPTH_EXCEEDED"
    CAPABILITY_NOT_PERMITTED = "CAPABILITY_NOT_PERMITTED"
    MUTATION_SCOPE_NOT_PERMITTED = "MUTATION_SCOPE_NOT_PERMITTED"
    INTEGRATION_REF_NOT_PERMITTED = "INTEGRATION_REF_NOT_PERMITTED"
    RUNTIME_PROFILE_NOT_PERMITTED = "RUNTIME_PROFILE_NOT_PERMITTED"
    REPAIR_ATTEMPTS_NOT_PERMITTED = "REPAIR_ATTEMPTS_NOT_PERMITTED"
    ROOT_CONTEXT_UNAVAILABLE = "ROOT_CONTEXT_UNAVAILABLE"
    ROOT_SCOPE_OVERLAP = "ROOT_SCOPE_OVERLAP"
    RISK_RELATION_UNAVAILABLE = "RISK_RELATION_UNAVAILABLE"
    RISK_NOT_PERMITTED = "RISK_NOT_PERMITTED"
    DELEGATION_NOT_PERMITTED = "DELEGATION_NOT_PERMITTED"
    ANCESTRY_INVALID = "ANCESTRY_INVALID"


class IssueContractAdmissionReasonCode(Enum):
    ADMITTED = "ADMITTED"
    SCHEMA_CONTEXT_UNAVAILABLE = "SCHEMA_CONTEXT_UNAVAILABLE"
    UNSUPPORTED_SCHEMA_BINDING = "UNSUPPORTED_SCHEMA_BINDING"
    POLICY_CONTEXT_UNAVAILABLE = "POLICY_CONTEXT_UNAVAILABLE"
    TARGET_CONTEXT_UNAVAILABLE = "TARGET_CONTEXT_UNAVAILABLE"
    CONTEXT_ANCHOR_UNAVAILABLE = "CONTEXT_ANCHOR_UNAVAILABLE"
    BASE_STATE_UNAVAILABLE = "BASE_STATE_UNAVAILABLE"
    CONFIG_CONTEXT_UNAVAILABLE = "CONFIG_CONTEXT_UNAVAILABLE"
    ROOT_CONTEXT_UNAVAILABLE = "ROOT_CONTEXT_UNAVAILABLE"
    REPAIR_POLICY_CONTEXT_UNAVAILABLE = "REPAIR_POLICY_CONTEXT_UNAVAILABLE"
    APPROVAL_ENFORCEMENT_UNAVAILABLE = "APPROVAL_ENFORCEMENT_UNAVAILABLE"
    UNSUPPORTED_REF_MODEL = "UNSUPPORTED_REF_MODEL"
    SCHEMA_BINDING_MISMATCH = "SCHEMA_BINDING_MISMATCH"
    CONTEXT_ANCHOR_MISMATCH = "CONTEXT_ANCHOR_MISMATCH"
    TARGET_REGISTRATION_MISMATCH = "TARGET_REGISTRATION_MISMATCH"
    TARGET_POLICY_EPOCH_MISMATCH = "TARGET_POLICY_EPOCH_MISMATCH"
    BASE_BINDING_MISMATCH = "BASE_BINDING_MISMATCH"
    ROOT_CONTEXT_BINDING_MISMATCH = "ROOT_CONTEXT_BINDING_MISMATCH"
    ROOT_SCOPE_OVERLAP = "ROOT_SCOPE_OVERLAP"
    ROOT_SCOPE_INDETERMINATE = "ROOT_SCOPE_INDETERMINATE"
    CONFIG_POLICY_EPOCH_MISMATCH = "CONFIG_POLICY_EPOCH_MISMATCH"
    CONFIG_BINDING_CHANGED = "CONFIG_BINDING_CHANGED"
    EVALUATOR_CONFIG_MISMATCH = "EVALUATOR_CONFIG_MISMATCH"
    EVALUATOR_PARAMETERS_INVALID = "EVALUATOR_PARAMETERS_INVALID"
    EVALUATOR_OPERATION_OUTSIDE_CONTRACT = "EVALUATOR_OPERATION_OUTSIDE_CONTRACT"
    RUNTIME_PROFILE_NOT_APPLICABLE = "RUNTIME_PROFILE_NOT_APPLICABLE"
    APPROVAL_OPERATION_OUTSIDE_CONTRACT = "APPROVAL_OPERATION_OUTSIDE_CONTRACT"
    REPAIR_POLICY_BINDING_MISMATCH = "REPAIR_POLICY_BINDING_MISMATCH"
    REPAIR_NOT_PERMITTED = "REPAIR_NOT_PERMITTED"
    REPAIR_ATTEMPTS_NOT_PERMITTED = "REPAIR_ATTEMPTS_NOT_PERMITTED"
    DELEGATION_NOT_PERMITTED = "DELEGATION_NOT_PERMITTED"


class G4FailureCode(Enum):
    """Closed lifecycle, revision, and cross-record failure domain for G4."""

    IDENTITY_MISMATCH = "IDENTITY_MISMATCH"
    REVISION_CONFLICT = "REVISION_CONFLICT"
    OPERATION_MEMBERSHIP_CONFLICT = "OPERATION_MEMBERSHIP_CONFLICT"
    TERMINAL_TASK = "TERMINAL_TASK"
    INVALID_TASK_TRANSITION = "INVALID_TASK_TRANSITION"
    INCONSISTENT_TASK_EVALUATION = "INCONSISTENT_TASK_EVALUATION"
    EVIDENCE_BINDING_MISMATCH = "EVIDENCE_BINDING_MISMATCH"
    CANDIDATE_DETACHMENT_UNSAFE = "CANDIDATE_DETACHMENT_UNSAFE"
    REPAIR_BUDGET_EXHAUSTED = "REPAIR_BUDGET_EXHAUSTED"
    REPAIR_ATTEMPT_REUSE_MISMATCH = "REPAIR_ATTEMPT_REUSE_MISMATCH"
    REPAIR_ATTEMPT_NOT_RESERVED = "REPAIR_ATTEMPT_NOT_RESERVED"
    OPERATION_ID_REUSE_MISMATCH = "OPERATION_ID_REUSE_MISMATCH"
    IDEMPOTENCY_COLLISION = "IDEMPOTENCY_COLLISION"
    INVALID_OPERATION_TRANSITION = "INVALID_OPERATION_TRANSITION"
    OPERATION_NOT_STARTABLE = "OPERATION_NOT_STARTABLE"
    CANCELLATION_BLOCKS_OPERATION_START = "CANCELLATION_BLOCKS_OPERATION_START"
    RECONCILIATION_REQUIRED = "RECONCILIATION_REQUIRED"
    ACTION_PRECONDITION_CONFLICT = "ACTION_PRECONDITION_CONFLICT"


@dataclass(frozen=True, slots=True)
class G4Failure:
    code: G4FailureCode

    def __post_init__(self) -> None:
        if type(self.code) is not G4FailureCode:
            raise TypeError("code must be exactly G4FailureCode")


@dataclass(frozen=True, slots=True)
class ParseFailure:
    code: ParseFailureCode
    detail: str | None = None

    def __post_init__(self) -> None:
        if type(self.code) is not ParseFailureCode:
            raise TypeError("code must be exactly ParseFailureCode")


@dataclass(frozen=True, slots=True)
class ManifestFailure:
    code: ManifestFailureCode
    parse_failure: ParseFailure | None = None

    def __post_init__(self) -> None:
        if type(self.code) is not ManifestFailureCode:
            raise TypeError("code must be exactly ManifestFailureCode")
        if self.parse_failure is not None and type(self.parse_failure) is not ParseFailure:
            raise TypeError("parse_failure must be exactly ParseFailure or None")


@dataclass(frozen=True, slots=True)
class ResourceFailure:
    code: ResourceFailureCode
    parse_failure: ParseFailure | None = None

    def __post_init__(self) -> None:
        if type(self.code) is not ResourceFailureCode:
            raise TypeError("code must be exactly ResourceFailureCode")
        if self.parse_failure is not None and type(self.parse_failure) is not ParseFailure:
            raise TypeError("parse_failure must be exactly ParseFailure or None")


@dataclass(frozen=True, slots=True)
class TargetRegistrationFailure:
    code: TargetRegistrationFailureCode
    parse_failure: ParseFailure | None = None

    def __post_init__(self) -> None:
        if type(self.code) is not TargetRegistrationFailureCode:
            raise TypeError("code must be exactly TargetRegistrationFailureCode")
        if self.parse_failure is not None and type(self.parse_failure) is not ParseFailure:
            raise TypeError("parse_failure must be exactly ParseFailure or None")


@dataclass(frozen=True, slots=True)
class AuthorizationProposalFailure:
    code: AuthorizationProposalFailureCode
    parse_failure: ParseFailure | None = None

    def __post_init__(self) -> None:
        if type(self.code) is not AuthorizationProposalFailureCode:
            raise TypeError("code must be exactly AuthorizationProposalFailureCode")
        if self.parse_failure is not None and type(self.parse_failure) is not ParseFailure:
            raise TypeError("parse_failure must be exactly ParseFailure or None")


@dataclass(frozen=True, slots=True)
class IssueContractFailure:
    code: IssueContractFailureCode
    parse_failure: ParseFailure | None = None

    def __post_init__(self) -> None:
        if type(self.code) is not IssueContractFailureCode:
            raise TypeError("code must be exactly IssueContractFailureCode")
        if self.parse_failure is not None and type(self.parse_failure) is not ParseFailure:
            raise TypeError("parse_failure must be exactly ParseFailure or None")


class IdentityValidationError(ValueError):
    """Construction failed lexical validation; it makes no external-state claim."""

    def __init__(self, code: IdentityValidationFailureCode) -> None:
        if type(code) is not IdentityValidationFailureCode:
            raise TypeError("code must be exactly IdentityValidationFailureCode")
        self.code = code
        super().__init__(code.value)
